### ISSUE TITLE
Support multiple files per locale in push and pull commands

### ISSUE THREAD

**Issue by bavdh** [localizely/localizely-cli#1]
Unable to push files to localizely.

### Expected behaviour:
```
$ localize-cli push --api-token <token> --project-id <project-id>
Successfully pushed data to Localizely
```

### Actual behaviour:
```
$ localize-cli push --api-token <token> --project-id <project-id>
Failed to push localization file 'i18n/templates/baz.po' to Localizely
Error: 400 Bad Request
```

Here is my configuration localizely.yml file
```
config_version: 1.0.2
file_type: po
upload:
  files:
  - file: i18n/templates/foo.po
    locale_code: en
  - file: i18n/templates/bar.po
    locale_code: en
  - file: i18n/templates/baz.po
    locale_code: en
download:
  files:
  - file: i18n/en/foo.po
    locale_code: en
  - file: i18n/ne/foo.po
    locale_code: ne
  - file: i18n/en/bar.po
    locale_code: en
  - file: i18n/ne/bar.po
    locale_code: ne
  - file: i18n/en/baz.po
    locale_code: en
  - file: i18n/ne/baz.po
    locale_code: ne
```
